/****** Script for SelectTopNRows command from SSMS  *****/
/* this is a query to select top 1000 in the X dep ****/
SELECT TOP (1000) [FacilityName]
      ,[ParentCompany]
      ,[ExecFirstName]
      ,[ExecLastName]
      ,[Address]
      ,[City]
      ,[State]
      ,[ZipCode]
      ,[ExecTitle]
      ,[FaxNumber]
      ,[EmployeeSize]
      ,[SalesVolume]
      ,[PrimarySICCode]
      ,[PrimarySICDescription]
      ,[SICCode1]
      ,[SICDescription1]
      ,[LegalName]
      ,[RecordType]
      ,[FacilityID]
  FROM [ALLYTRANSPORT].[dbo].[stg_MentalHealthFacilities]